config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "homes/about" => "homes#about",as: "about"

  resources :users, only: [:index, :show, :edit, :update]

  resources :books

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user, optional: true

  valodates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maxmum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.find(params[:id])
    @book.user.id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user.id = current_user.id
    if @book.update(book_params)
      flash[:notice]="You have updated book successfully."
      redirect_to :edit
    else
      render :edit
    end
  end

  def destroy
    @book = Book,find(params[:id])
    if @book.destroy
      redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = Book.all
    @books = Book.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<% form_with model: book do |f| %>

  <div class="form">
    <% f.label :Title %>
    <% f.text_field :title, class: "col-xs-12" %>
  </div>
  <div class="form">
    <% f.label :Opinion %>
    <% f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="form">
    <% f.submit "Create Book", class: "btn btn-success col-xs-12" %>
  </div>

<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
  <%= f.submit "Update Book", class: "btn btn-success" %>
  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", books_path %>
<% end %>

app/views/books/index.html.erb
<h2>Books</h2>
<table class="table">
  <thead>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th></th>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(book.user) do %>
          <%= image_tag @user.get_profile_image(50,50), fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td colspan="2"><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<h2>Book detail</h2>

<table class="table">
  <tr>
    <td>
      <%= image_tag @user.get_profile_image(25,25), fallback: "no_image.jpg" %><br>
      <%= link_to @user.name, user_path(@user) %>
    </td>
    <td><%= link_to @book.title %></td>
    <td><%= @book.body %></td>
    <% if @book.user_id == current_user.id %>
    <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success"  %></td>
    <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-danger" %></td>
    <% end %>
  </tr>
</table>

app/views/homes/about.html.erb
<h2>Welcome to <span>Bookers</span>!</h2>

app/views/homes/top.html.erb
<h2>Welcome to <span>Bookers</span>!!</h2>
<p>In <span>Bookers</span>,</p>
<p>
  you can share and exchange your opinions, inpressions, and emotions<>
  about various books!
</p>

app/views/layouts/_header.html.erb
<header>
  <h3><%= link_to "Bookers", root_path %></h3>
  <% if user_signed_in? %>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li>
    <li><%= link_to "Log in", new_user_session_path  %></li>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/a9c3784845.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>

<table class="table">
  <tr>
    <td><%= image_tag user.get_profile_image(50,50), fallback: "no_image.jpg" %></td>
  </tr>
  <tr>
    <td>name</td>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <td>introduction</td>
    <td><%= user.introduction %></td>
  </tr>
  <tr>
    <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog "></i>
    <% end %>
  </tr>
</table>

app/views/users/edit.html.erb
<h1>User info</h1>

<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label><br>
  <%= f.text_field :name, autofocus: true, id:"inputName" %>

  <label for="inputImage">Image</label><br>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>

  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction %><br>
  <%= f.submit "Update User", class: "btn btn-secondary" %>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
      <th>image</th>
      <th>name</th>
      <th></th>
  </thead>
  <tbody>
    <% @user.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(50,50), fallback: "no_image.jpg" %></td>
      <td><%= user.name %></td>
      <td><%= link_to "Show", "/users/#{user.id}" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h2>Books</h2>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td>
        <%= link_to user_path(@user) do %>
        <%= image_tag @user get_profile_image(100,100), fallback: "no_image.jpg" %>
        <% end %>
      </td>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>